@startuml
interface DataPersistence<Type> {
    + save(data: ArrayList<Type>): boolean
    + load(): ArrayList<Type>    
}
class FilePersistence<Type> {
    - filename: String
    + save(data: ArrayList<Type>): boolean
    + load(): ArrayList<Type>    
}
DataPersistence <|.. FilePersistence
class ItemList {
    + saveItems(): boolean
    + loadItems(): void
}
ItemList -left-> FilePersistence: <<bind>> Type: Item
class ContactList {
    + saveContacts(): boolean
    + loadContacts(): void
}
ContactList -left-> FilePersistence: <<bind>> Type: Contact
@enduml