@startuml
interface DataPersistence<Type> {
    + save(ArrayList<Type>): void
    + load(): ArrayList<Type>    
}
class FilePersistence<Type> {
    - filename: String
    + save(ArrayList<Type>): void
    + load(): ArrayList<Type>    
}
DataPersistence <|.. FilePersistence
class ItemList {

}
ItemList -left-> FilePersistence: <<bind>> Type: Item
class ContactList {

}
ContactList -left-> FilePersistence: <<bind>> Type: Contact
together {
    class ItemList
    class ContactList
}
' together {
'     interface DataPersistence<Type>
'     class FilePersistence<Type>
' }
@enduml